name: Release

permissions:
  contents: write

on:
  pull_request:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate a tag
      id: tag
      run: |
        tag=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
        echo "tag=v${tag}" >> "$GITHUB_OUTPUT"
    
    - name: Create a release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.tag.outputs.tag }}
        tag_name: ${{ steps.tag.outputs.tag }}
        generate_release_notes: true

    - name: Merge to main
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GH_TOKEN: ${{ github.token }}
      run: gh pr merge $PR_NUMBER --merge --auto
